---
- name : Deploy APP host & deploy app
  hosts: app
  vars:
    db_host : 51.250.84.102
  tasks:

    - name: Delete if exist
      file:
        state: absent
        path: /home/ubuntu/reddit

    - name: install git
      become: true
      apt:
        name: git
        state: present

    - name: Fetch the last version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload-puma

    - name: Bundler install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

    - name: Enable puma
      become: true
      systemd: daemon_reload=yes name=puma enabled=yes

  handlers:
     - name: reload-puma
       become: true
       systemd: name=puma state=restarted
