---
# - name: Add unit file for app
#   become: true
#   copy:
#     src: puma.service
#     dest: /etc/systemd/system/puma.service
#   notify: reload-puma

- name: Add unit file for app
  become: true
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
    mode: 0644
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  notify: reload-puma



- name: Add config file for puma
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    mode: 0644
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Enable puma
  become: true
  systemd: daemon_reload=yes name=puma enabled=yes
