---

- name : Configure DB host & deply app
  hosts: db-stage
  vars:
    mongo_bind_ip: 0.0.0.0
  become: true
  tasks:
    - name:  Change mongo DB config file
      template:
        src: templates/mongodb.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
        owner: ubuntu
        group: ubuntu
      notify: restart mongod

  handlers:
    - name: restart mongod
      service: name=mongod state=restarted
