---
- name: Installing Rubby
  hosts: default
  become: true
  tasks:
    - name: Installing Rubby and Bundler
      apt:
        state: present
        update_cache: yes
        name:
          - software-properties-common
          - ruby-full
          - ruby-bundler
          - build-essential
