Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "192.168.56.200"

    db.vm.provision "ansible" do |ansible|
    ansible.playbook = "/home/eugene/lerning/stage/ansible_main/playbooks/site_app.yml"
   # ansible.galaxy_role_path = "/home/eugene/lerning/stage/ansible_main/roles/db"
    ansible.config_file = "/home/eugene/lerning/stage/ansible_main/ansible.cfg"
    ansible.groups = {
    "db" => ["dbserver"],
    "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
    }
    end
  end


  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "192.168.56.201"

    app.vm.provision "ansible" do |ansible|
    ansible.playbook = "/home/eugene/lerning/stage/ansible_main/playbooks/site_app.yml"
    ansible.config_file = "/home/eugene/lerning/stage/ansible_main/ansible.cfg"
    ansible.groups = {
    "app" => ["appserver"],
    "app:vars" => { "db_host" => "192.168.56.200"}
 }
    ansible.extra_vars = {
    "deploy_user" => "ubuntu",
    "nginx_sites": {
          "default": [
            "listen 80",
            "server_name \"reddit\"",
            "location / {\nproxy_pass http://127.0.0.1:9292;}"
          ]

    }
  }


    end
  end
end
